# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: chuchu-z
subtitle: ''
description: '借君三十年，繁花万里好江山'
keywords: chuchu-z
author: chuchu-z
language: en
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://github.com/chuchu-z
root: /
permalink: posts/:id/ #:year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: true #在中文和英文之间加入空格
titlecase: false # Transform title into titlecase

external_link: # 在新标签中打开链接
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''

filename_case: 1 # 把文件名称转换为 (1) 小写或 (2) 大写, 默认0
render_drafts: false # 显示草稿
post_asset_folder: true # 启动 Asset 文件夹
relative_link: false # 把链接改为与根目录的相对位址
future: false # 显示未来文章

highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# indigo在hexo5.0及以上报错问题 https://github.com/yscoder/hexo-theme-indigo/issues/522
# theme: indigo # landscape
theme: indigo-hexo6 # landscape
stop_tag_plugins: true

feed:
  type: atom
  path: atom.xml
  limit: 0

jsonContent:
  # meta: false
  pages: false
  # posts:
  #   title: true
  #   date: true
  #   path: true
  #   text: true
  #   raw: false
  #   content: false
  #   slug: false
  #   updated: false
  #   comments: false
  #   link: false
  #   permalink: false
  #   excerpt: false
  #   categories: false
  #   tags: true

# search:
#   path: search.xml
#   field: post
#   format: html
#   limit: 10000

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  # repo: git@github.com:chuchu-z/chuchu-z.github.io.git #构建机器上没有配置 ssh 免密,所以使用https
  repo: https://github_token@github.com/chuchu-z/chuchu-z.github.io.git
  branch: master
  message: TravisCI 自动部署:{{ now('YYYY-MM-DD HH:ii:ss') }}
